### ISSUE TITLE
Add auto-generated files in the gitignore

### ISSUE THREAD

**Issue by thibaudszy** [HackYourFuture/Homework#79]
There are a bunch of files that get created when running npm tasks such as `install` or `test`, such as `sysinfo.json`. These are annoying when reviewing the homeworks as we always have to restore our branches before checking out another one. Some students also commit these files. 

Could we add the `test-runner.log` and `sysinfo.json` to the `.gitignore`?

**Comment by robvk** [comment]
Already handled in PRs
